#!/bin/bash

packageName="dbus-starlink"
source "/data/SetupHelper/HelperResources/IncludeHelpers"

if [ "$scriptAction" == 'INSTALL' ]; then
    logMessage "Making sure pip is available"
    opkg update
    opkg install python3-pip

    logMessage "Installing required python packages"
    pip3 install grpcio protobuf
fi

if [ "$scriptAction" == 'UNINSTALL' ]; then
    logMessage "Not removing python packages, as they may be used by other packages"
fi

endScript 'INSTALL_FILES' 'INSTALL_SERVICES' 'ADD_DBUS_SETTINGS'
