#!/bin/bash

packageName="dbus-starlink"
source "/data/SetupHelper/HelperResources/IncludeHelpers"

if [ "$scriptAction" == 'INSTALL' ]; then
    if [[ ! $(command -v pip3) ]]; then
        logMessage "pip3 not found, installing python3-pip"
        opkg update
        opkg install python3-pip
    fi

    logMessage "Installing required python packages"
    pip3 install grpcio protobuf
fi

if [ "$scriptAction" == 'UNINSTALL' ]; then
    logMessage "Not removing python packages, as they may be used by other packages"
fi

endScript 'INSTALL_FILES' 'INSTALL_SERVICES' 'ADD_DBUS_SETTINGS'
